export const RESULT_TYPE = {
  VIM_OBJECT: 'VIM_OBJECT',
  VIM_COLLECTION: 'VIM_COLLECTION',
  OBJECT: 'OBJECT',
  COLLECTION: 'COLLECTION',
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  ARRAY: 'ARRAY'
}

export default {
  RESULT_TYPE
}