export const XS = {
  anyType: {},
  anySimpleType: {},
  duration: {},
  dateTime: {},
  time: {},
  date: {},
  gYearMonth: {},
  gYear: {},
  gMonthDay: {},
  gDay: {},
  gMonth: {},
  boolean: {},
  base64Binary: {},
  hexBinary: {},
  float: {},
  double: {},
  anyURI: {},
  QName: {},
  NOTATION: {},
  string: {},
  deciman: {},
  normalizedString: {},
  integer: {},
  token: {},
  nonPositiveInteger: {},
  long: {},
  nonNegativeInteger: {},
  language: {},
  Name: {},
  NMTOKEN: {},
  negativeInteger: {},
  int: {},
  unsignedLong: {},
  positiveInteger: {},
  NCName: {},
  NMTOKENS: {},
  short: {},
  unsignedInt: {},
  ID: {},
  IDREF: {},
  ENTITY: {},
  byte: {},
  unsignedShort: {},
  IDREFS: {},
  ENTITIES: {},
  unsignedByte: {}
}

export default {
  XS
}